server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/micro
    username: micro
    password: micro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${LOG_SQL:false}
    open-in-view: false
    database: postgresql
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}