server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/{cipher}4c0213693c9b800108aa1a0e6989c14e19b5f4c54731fbc6bb01d4afe741adc6
    username: {cipher}4c0213693c9b800108aa1a0e6989c14e19b5f4c54731fbc6bb01d4afe741adc6
    password: {cipher}4c0213693c9b800108aa1a0e6989c14e19b5f4c54731fbc6bb01d4afe741adc6
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${LOG_SQL:false}
    open-in-view: false
    database: postgresql
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}